language: node_js
dist: xenial
sudo: required

matrix:
  include:
    - name: Postgresql 10
      addons:
        postgresql: "10"

node_js:
  - "10"

before_script:
- psql -c 'create database travis_tester;' -U postgres

script:
  - npm test
