language: node_js
dist: xenial
sudo: required

matrix:
  include:
    - name: Postgresql 9.6
      env:
        - PGPORT=5432
      addons:
        postgresql: "9.6"
    - name: Postgresql 10
      env:
        - PGPORT=5432
      addons:
        postgresql: "10"
    - name: Postgresql 11
      env:
        - PGPORT=5433
      addons:
        postgresql: "11"


env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=postgres

node_js:
  - "10"

script:
  - npm test
