language: node_js
dist: xenial
sudo: required

matrix:
  include:
    - name: Postgresql 9.6
      addons:
        postgresql: "9.6"
    - name: Postgresql 10
      addons:
        postgresql: "10"
    - name: Postgresql 11
      addons:
        postgresql: "11"


env:
  global:
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=postgres

node_js:
  - "10"

script:
  - npm test
