language: node_js

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

node_js:
  - "10"

env:
  global:
    - PGPORT=5433
    - PGUSER=postgres
    - PGPASSWORD=postgres

before_install:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart

before_script:
  - psql -c 'create database okay_test' -U postgres

script:
  - npm test
