language: node_js

sudo: required

services:
  - postgresql

matrix:
  include:
    - name: Postgresql 10
      addons:
        postgresql: "10"

node_js:
  - "10"

before_script:
  - psql -c 'create database okay_test' -U postgres

script:
  - npm test
